name: Deploy blue

on:
  deployment:

jobs:
  prepare:
    name: ${{ github.event.deployment.environment }} deployment in progress
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          console.log(JSON.stringify(context))
          sleep 60